- name: test my new module
  hosts: localhost
  tasks:
  - name: run the new module
    my_test:
      name: 'amr'
      new: true
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'
